// Generated by Framer (e182fd8)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
	withFX,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import Loader from "https://framerusercontent.com/modules/WWgepZ53F0UvvW2fDAoG/9AlSFL6dAzTVzS4oiWbM/APim4rHnB.js";
const LoaderFonts = getFonts(Loader);
const MotionDivWithFX = withFX(motion.div);
const cycleOrder = ["iX0mOkYCI", "kXCYVWtY9", "itXzaPKMZ"];
const serializationHash = "framer-kqtbX";
const variantClassNames = {
	itXzaPKMZ: "framer-v-1429lgn",
	iX0mOkYCI: "framer-v-1nl18og",
	kXCYVWtY9: "framer-v-uqmi5u",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) => variant && Object.assign(nextOverrides, overrides[variant])
		  );
	return nextOverrides;
}
const transition1 = {
	delay: 0,
	duration: 0.25,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
const transition2 = {
	delay: 0,
	duration: 0.7,
	ease: [0.5, 0, 0.88, 0.77],
	type: "tween",
};
const animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
const Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({ ...config, transition }),
		[JSON.stringify(transition)]
	);
	return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
		value: contextValue,
		children: children,
	});
};
const Variants = motion(React.Fragment);
const humanReadableVariantMap = {
	"Back Up": "iX0mOkYCI",
	"Backing Up": "kXCYVWtY9",
	Done: "itXzaPKMZ",
};
const getProps = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "iX0mOkYCI",
	};
};
const createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "iX0mOkYCI",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1blzyeq = activeVariantCallback(async (...args) => {
		setGestureState({ isPressed: false });
		setVariant("kXCYVWtY9");
	});
	const onAppearkmsas5 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("itXzaPKMZ"), 2800);
	});
	const onAppearbf9nj8 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("iX0mOkYCI"), 1500);
	});
	useOnVariantChange(baseVariant, {
		itXzaPKMZ: onAppearbf9nj8,
		kXCYVWtY9: onAppearkmsas5,
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return /*#__PURE__*/ _jsx(LayoutGroup, {
		id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
		children: /*#__PURE__*/ _jsx(Variants, {
			animate: variants,
			initial: false,
			children: /*#__PURE__*/ _jsx(Transition, {
				value: transition1,
				children: /*#__PURE__*/ _jsxs(motion.button, {
					...restProps,
					className: cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-1nl18og",
						className,
						classNames
					),
					"data-framer-name": "Back Up",
					"data-highlight": true,
					"data-reset": "button",
					layoutDependency: layoutDependency,
					layoutId: "iX0mOkYCI",
					onHoverEnd: () => setGestureState({ isHovered: false }),
					onHoverStart: () => setGestureState({ isHovered: true }),
					onTap: onTap1blzyeq,
					onTapCancel: () => setGestureState({ isPressed: false }),
					onTapStart: () => setGestureState({ isPressed: true }),
					ref: ref !== null && ref !== void 0 ? ref : ref1,
					style: {
						backgroundColor: "rgb(8, 189, 113)",
						borderBottomLeftRadius: 1e3,
						borderBottomRightRadius: 1e3,
						borderTopLeftRadius: 1e3,
						borderTopRightRadius: 1e3,
						boxShadow:
							"inset 0px 1px 0px 0px rgba(255, 255, 255, 0.2), inset 0px -1px 0px 0px rgba(0, 0, 0, 0.15)",
						...style,
					},
					...addPropertyOverrides(
						{
							itXzaPKMZ: {
								"data-framer-name": "Done",
								onTap: () => setGestureState({ isPressed: false }),
							},
							kXCYVWtY9: {
								"data-framer-name": "Backing Up",
								onTap: () => setGestureState({ isPressed: false }),
							},
						},
						baseVariant,
						gestureVariant
					),
					children: [
						/*#__PURE__*/ _jsx(ComponentViewportProvider, {
							width: "20px",
							children: /*#__PURE__*/ _jsx(motion.div, {
								className: "framer-5o5uiy-container",
								layoutDependency: layoutDependency,
								layoutId: "Vc0WWAnzv-container",
								style: { opacity: 0, scale: 0.6 },
								variants: {
									itXzaPKMZ: { opacity: 1, scale: 1 },
									kXCYVWtY9: { opacity: 1, scale: 1 },
								},
								children: /*#__PURE__*/ _jsx(Loader, {
									height: "100%",
									id: "Vc0WWAnzv",
									layoutId: "Vc0WWAnzv",
									PuQ5WOk1G: 0,
									style: { height: "100%", width: "100%" },
									variant: "ZjE38YABk",
									width: "100%",
									...addPropertyOverrides(
										{
											itXzaPKMZ: { PuQ5WOk1G: 1 },
											kXCYVWtY9: { variant: "SnriyRbot" },
										},
										baseVariant,
										gestureVariant
									),
								}),
							}),
						}),
						/*#__PURE__*/ _jsx(RichText, {
							__fromCanvasComponent: true,
							children: /*#__PURE__*/ _jsx(React.Fragment, {
								children: /*#__PURE__*/ _jsx(motion.p, {
									style: {
										"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
										"--framer-font-family":
											'"Inter", "Inter Placeholder", sans-serif',
										"--framer-font-weight": "600",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255)))",
									},
									children: "Back Up Now",
								}),
							}),
							className: "framer-1v0srvh",
							fonts: ["Inter-SemiBold"],
							layoutDependency: layoutDependency,
							layoutId: "zANh7D9yX",
							style: {
								"--extracted-r6o4lv":
									"var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
								textShadow: "0px 0.5px 0px rgba(0, 0, 0, 0.15)",
							},
							verticalAlignment: "top",
							withExternalLayout: true,
							...addPropertyOverrides(
								{
									itXzaPKMZ: {
										children: /*#__PURE__*/ _jsx(React.Fragment, {
											children: /*#__PURE__*/ _jsx(motion.p, {
												style: {
													"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
													"--framer-font-family":
														'"Inter", "Inter Placeholder", sans-serif',
													"--framer-font-weight": "600",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255)))",
												},
												children: "Backing Up",
											}),
										}),
									},
									kXCYVWtY9: {
										children: /*#__PURE__*/ _jsx(React.Fragment, {
											children: /*#__PURE__*/ _jsx(motion.p, {
												style: {
													"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
													"--framer-font-family":
														'"Inter", "Inter Placeholder", sans-serif',
													"--framer-font-weight": "600",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255)))",
												},
												children: "Backing Up",
											}),
										}),
									},
								},
								baseVariant,
								gestureVariant
							),
						}),
						/*#__PURE__*/ _jsx(MotionDivWithFX, {
							__framer__loop: animation,
							__framer__loopEffectEnabled: true,
							__framer__loopRepeatDelay: 0,
							__framer__loopRepeatType: "mirror",
							__framer__loopTransition: transition2,
							__perspectiveFX: false,
							__smartComponentFX: true,
							__targetOpacity: 1,
							className: "framer-ped7qc",
							"data-border": true,
							"data-framer-name": "Ring 1",
							layoutDependency: layoutDependency,
							layoutId: "pCXPBARQA",
							style: {
								"--border-bottom-width": "2px",
								"--border-color": "rgb(8, 189, 113)",
								"--border-left-width": "2px",
								"--border-right-width": "2px",
								"--border-style": "solid",
								"--border-top-width": "2px",
								borderBottomLeftRadius: 1e3,
								borderBottomRightRadius: 1e3,
								borderTopLeftRadius: 1e3,
								borderTopRightRadius: 1e3,
								opacity: 1,
							},
							tabIndex: -1,
							variants: { itXzaPKMZ: { opacity: 0 } },
							...addPropertyOverrides(
								{ itXzaPKMZ: { __targetOpacity: 0 } },
								baseVariant,
								gestureVariant
							),
						}),
					],
				}),
			}),
		}),
	});
});
const css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-kqtbX.framer-1bdwa5h, .framer-kqtbX .framer-1bdwa5h { display: block; }",
	".framer-kqtbX.framer-1nl18og { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: 44px; justify-content: center; overflow: visible; padding: 0px 16px 0px 16px; position: relative; width: min-content; }",
	".framer-kqtbX .framer-5o5uiy-container { flex: none; height: 20px; left: 16px; pointer-events: none; position: absolute; top: calc(50.00000000000002% - 20px / 2); width: 20px; z-index: 1; }",
	".framer-kqtbX .framer-1v0srvh { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-kqtbX .framer-ped7qc { -webkit-user-select: none; bottom: -6px; flex: none; left: -6px; overflow: hidden; pointer-events: none; position: absolute; right: -6px; top: -6px; user-select: none; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-kqtbX.framer-1nl18og { gap: 0px; } .framer-kqtbX.framer-1nl18og > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-kqtbX.framer-1nl18og > :first-child { margin-left: 0px; } .framer-kqtbX.framer-1nl18og > :last-child { margin-right: 0px; } }",
	".framer-kqtbX.framer-v-uqmi5u .framer-5o5uiy-container, .framer-kqtbX.framer-v-1429lgn .framer-5o5uiy-container { left: unset; position: relative; top: unset; }",
	'.framer-kqtbX[data-border="true"]::after, .framer-kqtbX [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 44
 * @framerIntrinsicWidth 134.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"kXCYVWtY9":{"layout":["auto","fixed"]},"itXzaPKMZ":{"layout":["auto","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerFgA6cz892 = withCSS(Component, css, "framer-kqtbX");
export default FramerFgA6cz892;
FramerFgA6cz892.displayName = "Button";
FramerFgA6cz892.defaultProps = { height: 44, width: 134.5 };
addPropertyControls(FramerFgA6cz892, {
	variant: {
		options: ["iX0mOkYCI", "kXCYVWtY9", "itXzaPKMZ"],
		optionTitles: ["Back Up", "Backing Up", "Done"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerFgA6cz892,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-SemiBold.cyrillic-ext-C7KWUKA7.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-SemiBold.cyrillic-JWV7SOZ6.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-SemiBold.greek-ext-FBKSFTSU.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-SemiBold.greek-EQ3PSENU.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-SemiBold.latin-ext-ULRSO3ZR.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-SemiBold.latin-RDYY2AG2.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-SemiBold.vietnamese-ESQNSEQ3.woff2",
					weight: "600",
				},
			],
		},
		...LoaderFonts,
	],
	{ supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
	exports: {
		Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
		default: {
			type: "reactComponent",
			name: "FramerFgA6cz892",
			slots: [],
			annotations: {
				framerComponentViewportWidth: "true",
				framerImmutableVariables: "true",
				framerDisplayContentsDiv: "false",
				framerIntrinsicWidth: "134.5",
				framerContractVersion: "1",
				framerCanvasComponentVariantDetails:
					'{"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"kXCYVWtY9":{"layout":["auto","fixed"]},"itXzaPKMZ":{"layout":["auto","fixed"]}}}',
				framerIntrinsicHeight: "44",
			},
		},
		__FramerMetadata__: { type: "variable" },
	},
};
//# sourceMappingURL=./FgA6cz892.map
